import { api } from '@/lib/api';
import StatusBadge from '@/components/dashboard/StatusBadge';
import EmptyState from '@/components/dashboard/EmptyState';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Progress } from "@/components/ui/progress";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"

export default async function SignalsPage({
  searchParams,
}: {
  searchParams: { symbol?: string; timeframe?: string };
}) {
  const symbol = searchParams.symbol || 'XAUUSD';
  const timeframe = searchParams.timeframe || '';
  
  const signals = await api.getSignalHistory(symbol, timeframe) || [];

  return (
    <div className="space-y-8">
      <div className="flex flex-col gap-4 md:flex-row md:justify-between md:items-center">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Signal History</h2>
          <p className="text-muted-foreground mt-1">Review historical signals generated by the AI models.</p>
        </div>
      </div>

      <Card>
        <CardHeader className="bg-muted/30 border-b pb-4">
          <div className="flex gap-4">
            <div className="space-y-1.5 w-48">
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Symbol Filter</label>
              <Select disabled defaultValue={symbol}>
                <SelectTrigger>
                  <SelectValue placeholder="Select symbol" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="XAUUSD">XAUUSD</SelectItem>
                  <SelectItem value="NQ100">NQ100</SelectItem>
                  <SelectItem value="BTCUSD">BTCUSD</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {signals.length === 0 ? (
            <div className="p-8">
              <EmptyState message={`No signals found for ${symbol}.`} />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[180px]">Time</TableHead>
                  <TableHead>Strategy</TableHead>
                  <TableHead>TF</TableHead>
                  <TableHead>Direction</TableHead>
                  <TableHead className="w-[200px]">Confidence</TableHead>
                  <TableHead className="text-right">Entry Price</TableHead>
                  <TableHead className="text-right">Session</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {signals.map((sig: any, i: number) => (
                  <TableRow key={i}>
                    <TableCell className="text-muted-foreground">{sig.recorded_at}</TableCell>
                    <TableCell className="font-medium">{sig.strategy}</TableCell>
                    <TableCell>{sig.timeframe}</TableCell>
                    <TableCell>
                      <StatusBadge status={sig.direction} />
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-3">
                        <span className="text-xs font-medium w-8">{sig.confidence ? `${sig.confidence.toFixed(0)}%` : '-'}</span>
                        {sig.confidence && (
                           <Progress value={sig.confidence} className="h-2" />
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-right font-mono">{sig.entry_price ? sig.entry_price.toFixed(2) : '-'}</TableCell>
                    <TableCell className="text-right text-muted-foreground">{sig.session || '-'}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
